### ISSUE TITLE
rescue in get_label': Label too long (74, max length=63)

### ISSUE THREAD

**Issue by KINGSABRI** [alexdalitz/dnsruby#106]
First, Thanks for making Dnsruby that much mature and awesome

I'm trying to PTR `207. 46.197.32` address which is originally the `owa.zonetransfer.me` IP. 

when I do the following 

``` ruby
resolver = Dnsruby::Resolver.new
query     = resolver.query('207.46.197.32', 'PTR', 'IN')
```

It trigers the following error

```
Dnsruby::DecodeError: Label too long (115, max length=100). Label = anslimite��
                                                                               �everyonegetsit��
responsepoint�  �                                                                               �
                 �xn--frdermittel-ratgeber-39bƕ�
from /var/lib/gems/2.3.0/gems/dnsruby-1.59.3/lib/dnsruby/message/decoder.rb:149:in `rescue in get_label'
```

However, using `host` command

```
host -t ptr 207.46.197.32
```

It returns all the PTRs which are 1042 ptr

```
32.197.46.207.in-addr.arpa domain name pointer msdnchallenge.com.
32.197.46.207.in-addr.arpa domain name pointer mobileservices.info.
32.197.46.207.in-addr.arpa domain name pointer windowsxp.com.gt.
.
.
.
32.197.46.207.in-addr.arpa domain name pointer windowsxp.org.mu.
32.197.46.207.in-addr.arpa domain name pointer windowsruby.com.pl.
32.197.46.207.in-addr.arpa domain name pointer windowsruby.com.sg.
```

I tried to update the MaxLabelLength, which is bad and I should not do that and still not working

``` ruby
Dnsruby::Name::Label::MaxLabelLength = 2000
```

How I may fix this?

**Comment by alexdalitz** [comment]
Hi- 

Sorry for the delayed response.

I can’t run this query here - could you please tell me if the current master fixes this problem?

Thanks,


Alex.

**Comment by KINGSABRI** [comment]
Hi! 
Yes, it's the same issue with the master 


btw, I love your coding style

**Comment by alexdalitz** [comment]
OK thanks for testing. Sadly, I'm having trouble connecting over tcp to the server, so I'm not able to reproduce the problem here. It would be extremely helpful if you could please send the packet which is tripping it up?

BTW, I'm surprised at the "max length = 100" in your snippet above. I would have expected it to be 63...

Thanks!

**Comment by alexdalitz** [comment]
Hey just to say I've now managed to connect, so I hope to fix this soon.

**Comment by alexdalitz** [comment]
A quick update to say I _am_ still looking at this. My suspicion is that there is an issue reconnecting the TCP packets. The error always occurs _after_ byte 1600, and is always in a backwards name pointer to a label _before_ 1600 - although many backwards pointers from after 1600 for before 1600 _do_ work. So I'm slightly confused...

**Comment by KINGSABRI** [comment]
Hi, now I'm getting 
```ruby
query     = resolver.query('207.46.197.32', 'PTR', 'IN')
Dnsruby::ResolvTimeout: Query timed out
from /var/lib/gems/2.3.0/gems/dnsruby-1.59.3/lib/dnsruby/resolver.rb:256:in `send_message'
```

**Comment by alexdalitz** [comment]
That sounds like it is a failure to connect over TCP. I have that, if I go through my Ubiquiti Edge Router, which appears to block DNS TCP connections by default. If it is that, then you will find the host command also times out from that network.

**Comment by KINGSABRI** [comment]
Mmm, why and when it uses TCP connection?

**Comment by alexdalitz** [comment]
It uses TCP because the packet is too big to fit into a UDP packet, so the TC bit is set on the original UDP response header. This instructs the client to try again over TCP (to handle the full response packet). This DNS TCP connection is sometimes blocked by some part of the network. If this happens, then the query will time out.

I think the problem with the decoding is that the packet has been reassembled slightly incorrectly, leading to a problem when looking for a label using the backward name pointer. To save space in the packet, it is possible for names to point to previously occurring labels (e.g. ".co.uk" might follow "bbc" - since ".co.uk" may have appeared before in the response, the label "bbc" may be followed by a pointer to the previous occurrence).

The decoding issue is that the backwards pointer appears to be pointing to the middle of a label, rather than the length byte which should precede the label. I've not yet managed to ascertain quite why this is, but I am working on it (although I'm afraid to say that my limited available time is not helping to get this fixed fast).

**Comment by alexdalitz** [comment]
So I've traced through a sample, and the pointers do indeed appear to be corrupted. However, the binary I'm looking at is the binary dnsruby has collected from the TCP interface - at this point, I have to assume that this is corrupted, and that the actual binary is both different and also contains happy pointers. As of yet, I haven't had the time to compare the original wireshark binary against the dnsruby interpretation of it. I wonder if @nwitkowski is able to help with understanding why the TCP received long messages contain corrupt pointers?

**Comment by nwitkowski** [comment]
So I devised the following test:
```Ruby
require_relative 'spec_helper'

include Dnsruby
class TestPtrIn < Minitest::Test
  def test_ptr_in
    Dnsruby.log.level = Logger::DEBUG

    #example.com A IN (2-byte size removed at beginning)
    hex = "f8f681900001000200030005076578616d706c6503636f6d0000010001c00c0001000100014f0c00045db8d822c00c002e000100014f0c00a20001080200015180580ec93f57f38df906a8076578616d706c6503636f6d006ae1882b1536a15c44f5813671af57bf9cae0366cff2ec085d6dedfddff0c469fa827ceec953de7cc1eee634f4cf695dc2caa2074f95199a5582e51e63b336d8f091d18c0c1a307ae3f5508ec650c4085a95e54e2c2451d9fc9ae04b4e62f3d1a1689e9507c3692fb84817a70afd3e9cdf066f73cc4ac11ed080a30d2af31510b457b5c04b0002000100014f0c001401620c69616e612d73657276657273036e657400c04b0002000100014f0c00040161c0e9c04b002e000100014f0c00a2000208020001518058109f4c57f56c1906a8076578616d706c6503636f6d006d8dd0fdbd0a0b0bfe7e4306a4a001bb7a13df2faedb1702a329243c326b915191335e99e16a236de99360547efa96ec6ee547a6dcfab94b57de6f7891bcaf99a2ef5d3c72d5bc18d1bf05ff4473f527bd8f2e6621489ab531dfb6a973e37e0f0be52740a362599058b204097a04c96492e527bfca6a22338eb865b51156c2ab0e6940c10700010001000004940004c72b8735c107001c00010001e209001020010500008f00000000000000000053c0e700010001000004940004c72b8535c0e7001c00010001e209001020010500008d000000000000000000530000291000000080000000"

    Message.decode([hex].pack('H*').force_encoding("ASCII-8BIT"))

    #32.197.46.207.in-addr.arpa: type PTR, class IN (2-byte size removed at beginning) 
    hex = "511f81900001041200040007023332033139370234360332303707696e2d61646472046172706100000c0001c00c000c00010000071900140c6f666669636573797374656d02636f026e7a00c00c000c00010000071900130d72656e636f6e7472652d333630036f726700c00c000c00010000071900120c6d6f6e2d7061636b2d70726f036e657400c00c000c000100000719001a1777696e646f77736d6f62696c65636f6d6d6d756e697479c084c00c000c000100000719001b126d6963726f736f6674666f726566726f6e7403636f6d026d7900c00c000c00010000071900191677696e646f7773647269766572646576656c6f706572c084c00c000c00010000071900282277696e646f7773647269766572646576656c6f706d656e74636f6e666572656e636503636f6d00c00c000c00010000071900100d706f776572746f676574686572c12ac00c000c00010000071900120d6d6963726f736f6674686f6d6502636100c00c000c00010000071900161372656c6576657a746f75736c65736465666973c084c00c000c0001000007190016136f666672652d65626c6f75697373616e746573c084c00c000c000100000719001b126d6963726f736f6674666f726566726f6e7403636f6d02686b00c00c000c0001000007190017126d6963726f736f6674666f726566726f6e7402757300c00c000c00010000071900151277696465776f726c64696d706f7274657273c066c00c000c0001000007190017126d6963726f736f6674666f726566726f6e7402646500c00c000c0001000007190014116d6f62696c657063646576656c6f706572c084c00c000c000100000719000d0a6d7366746d6f62696c65c084c00c000c00010000071900150d77696e646f77736d6f62696c6502636f02756b00c00c000c00010000071900161372656c6576657a746f75736c65736465666973c12ac00c000c00010000071900100d6c6573626f6e736f7574696c73c066c00c000c000100000719000e0b6d756e63686f6e74686973c12ac00c000c000100000719001613736d61727470686f6e65636f6d6d756e697479c084c00c000c00010000071900131074686570686f6e652d636f6d70616e79c12ac00c000c00010000071900140f6d7977696e646f77736d6f62696c6502626500c00c000c00010000071900191677696e646f77736d6f62696c65636f6d6d756e697479c084c00c000c00010000071900150d77696e646f77736d6f62696c6502636f026b7200c00c000c00010000071900191677696e646f77736d6f62696c65636f6d6d756e697479c066c00c000c000100000719000a0772656d69783038c066c00c000c00010000071900161372656c65766572746f75736c65736465666973c12ac00c000c000100000719000f0c6d6f6e2d7061636b2d70726fc066c00c000c00010000071900110e726973656f667065726174686961c12ac00c000c000100000719001b1877696e646f7773647269766572646576656c6f706d656e74c066c00c000c000100000719000805776d766864c12ac00c000c0001000007190017126d6963726f736f6674666f726566726f6e7402706c00c00c000c00010000071900191677696e646f7773647269766572646576656c6f706572c12ac00c000c0001000007190017126d6963726f736f6674666f726566726f6e7402696e00c00c000c0001000007190014116d616e6167656669786564617373657473c066c00c000c00010000071900120f6865726f7368617070656e68657265c045c00c000c000100000719001b126d6963726f736f6674666f726566726f6e7403636f6d026d7800c00c000c000100000719001a176d6963726f736f6674627573696e657373617761726473c084c00c000c0001000007190017126d6963726f736f6674666f726566726f6e7402706800c00c000c00010000071900120f736572766572756e6c656173686564c066c00c000c000100000719000b086d6170706f696e74c084c00c000c000100000719000f0c747265797265736561726368c066c00c000c0001000007190015127465636e6f6c6f67696179656d7072657361c12ac00c000c000100000719000b086d6163746f706961c12ac00c000c00010000071900100d776f6f6467726f766562616e6bc066c00c000c0001000007190019166d69677265727665727376697375616c73747564696fc084c00c000c00010000071900110e72656e636f6e747265732d333630c084c00c000c00010000071900181372656c6576657a746f75736c6573646566697302667200c00c000c000100000719000c09697462727565636b65c084c00c000c0001000007190014116d6963726f736f66746d6f6d656e74756dc12ac00c000c00010000071900140f73657276657273636174656e61746f02697400c00c000c000100000719000d0a796f7572746563686564c12ac00c000c00010000071900252277696e646f7773647269766572646576656c6f706d656e74636f6e666572656e6365c066c00c000c000100000719001a1777696e646f77736d6f62696c65636f6d6d6d756e697479c12ac00c000c00010000071900120f6d7977696e646f77736d6f62696c65c165c00c000c00010000071900120d77696e646f77736d6f62696c6502657300c00c000c00010000071900161372656c6576657a746f75736c65736465666973c165c00c000c00010000071900150f6d6963726f736f66746d6f62696c650362697a00c00c000c00010000071900110e726973656f667065726174686961c084c00c000c000100000719000d0a77696e7465726e616c73c084c00c000c000100000719001310746f646f736c6f656e7469656e64656ec066c00c000c000100000719000a077265736b6976c6f676fc12ac00c000c00010000071900120f736572766572756e6c656173686564c084c00c000c000100000719001a176d6963726f736f66742d6272616e6368656e766964656fc237c00c000c0001000007190008056d7365707100000719000e0b696e6e6f766174652d756bc066c00c000c00010000071900120f736572766572756e6c656173686564c12ac00c000c00010000071900252277696e6000c000100000719000e0977696e646f77736e7402636600c00c000c000100000719000c09746563686564766970c12ac00c000c00010000071900120977696e646f77736e74036e657402766900c00c000c000100000719000e0b7769c000100000719000e0b77696e646f777372756279e2d8c00c000c000100000719000906666c6578676fe2d8c00c000c00010000071900110c77696e646f77737669737461026c6100c00c000c00010000071900110b77696e646f777376d6d756e697479617761726473c12ac00c000c000100000719000e0b77696e646f777372756279d7f3c00c000c00010000071900180f65756772616e747361647669013106865726f657368617070656e68657265c483c00c000c00010000071900120d726573706f6e7365706f696e7402646d00c00c000c000100000719000c0977696e646f77737870d9bfc00c000c000100000719000c0977696e646f7c00c000c000100000719000f06616d616c676103636f6d02707300c00c000c0001000007c000c0001000007196e616e636573c12ac00c000c0001000007190f6e74c483c00c000c000100000719001411674666f726566726f6e74d6d4c00c000c0001000007190019166772617068696364657369676e696e73746974757465c066c00c000c00010000071900120f6f6e6c696e6573706f746c69676874c066c00c000c000100000719000e0b6374726f726f6e74c28ec00c000c000100000719001a176d6963726f736f6674627573696e657373617761726473c12ac00c000c0001000007190016136e6f74666f7270726f6669746e646f7773d6d4c00c000c0001000007190015126d6963726f736f6674666f726566726f6e74ea5cc00c000c0001000007190015126d6963726f736f6674666f726566726f6e74dba8c00c000c0001000007190014116d6963726f736f667464796e616d696373c683c00c000c00010000071900151277696465776f726c64696d706f7274657273c084c00c000c000100000719000e0b6d756e63686f6e74686973c066c00c000c000100000719000c0970726f736577617265c066c00c000c0001000007190019166d69677265727665727376697375616c73747564696fc12ac00c000c0001000007190015126d6963726f736f6674666f726566726f6e74f4a0c00c000c000100000719000d0a6d7366746d6f62696c65c066c00c000c000100000719000b086e61766973696f6ed3f0c00c000c00010000071900100d72656e636f6e74726573333630c066c00c000c00010000071900110e6a65646572686174736472617566c237c00c000c0001000007190015126d6963726f736f6674666f726566726f6e74fdabc00c000c0001000007190015126c6573646f6967747364616e736c656e657ac084c00c000c0001000007190014116d616e6167656669786564617373657473c084c00c000c00010000071900120f6d73646e746563686e6574746f7572c084c00c000c000100000719001c196d6963726f736f66746c6963656e736573746174656d656e74c165c00c000c000100000719000a0777696e646f7773c084c00c000c0001000007190015126d6963726f736f6674666f726566726f6e74e695c00c000c00010000071900120f6d73646e746563686e6574746f7572c12ac00c000c00010000071900120f6d7977696e646f77736d6f62696c65de62c00c000c000100000719001c196d6963726f736f66746c6963656e736573746174656d656e74c12ac00c000c0001000007190016136f666672652d65626c6f75697373616e746573c066c00c000c0001000007190015126f666672652d65626c6f75697373616e7465c066c00c000c000100000719000f0c6d6963726f736f6674646f70c084c00c000c0001000007190015126d737368617265706f696e74666f72756d73c084c00c000c000100000719001714706c75736465343030646966666572656e636573c165c00c000c00010000071900191677696e646f77736d6f62696c65636f6d6d756e697479c12ac00c000c000100000719000e0b77696e67746970746f7973c12ac00c000c000100000719001b1877696e646f7773647269766572646576656c6f706d656e74c12ac00c000c0001000007190015127465636e6f6c6f67696179656d7072657361c066c00c000c0001000007190015126d6963726f736f6674666f726566726f6e74d0e0c00c000c0001000007190015126d6963726f736f6674666f726566726f6e74c1d0c00c000c0001000007190015126d6963726f736f6674666f726566726f6e74dba4c00c000c000100000719000b0872656d69782d3038c084c00c000c000100000719000d0a77696e7465726e616c73c066c00c000c0001000007190015126d737368617265706f696e74666f72756d73c066c00c000c000100000719"

    Message.decode([hex].pack('H*').force_encoding("ASCII-8BIT"))

  end
end
```
First query, example.com (copied from wireshark) passes
Second query, resolver.query('207.46.197.32', 'PTR', 'IN'), reassembled from wireshark and size removed (770B at the beginning) fails with the following error:
```
  1) Error:
TestPtrIn#test_ptr_in:
Dnsruby::DecodeError: non-backward name pointer
    /home/deploy/dnsruby/lib/dnsruby/message/decoder.rb:130:in `get_labels'
    /home/deploy/dnsruby/lib/dnsruby/message/decoder.rb:114:in `get_name'
    /home/deploy/dnsruby/lib/dnsruby/resource/domain_name.rb:52:in `decode_rdata'
    /home/deploy/dnsruby/lib/dnsruby/message/decoder.rb:171:in `block in get_rr'
    /home/deploy/dnsruby/lib/dnsruby/message/decoder.rb:53:in `get_length16'
    /home/deploy/dnsruby/lib/dnsruby/message/decoder.rb:171:in `get_rr'
    /home/deploy/dnsruby/lib/dnsruby/message/message.rb:575:in `block (2 levels) in decode'
    /home/deploy/dnsruby/lib/dnsruby/message/message.rb:574:in `times'
    /home/deploy/dnsruby/lib/dnsruby/message/message.rb:574:in `block in decode'
    /home/deploy/dnsruby/lib/dnsruby/message/decoder.rb:20:in `initialize'
    /home/deploy/dnsruby/lib/dnsruby/message/message.rb:568:in `new'
    /home/deploy/dnsruby/lib/dnsruby/message/message.rb:568:in `decode'
    /home/deploy/dnsruby/test/tc_ptrin.rb:16:in `test_ptr_in'
```
I basically copied the dns string (possibly reassembled) as hex stream from wireshark to the test case and removed the first 2 bytes that corresponds to the size.
This is from master.

**Comment by nwitkowski** [comment]
Never mind. I had a copy paste error. The decoder works correctly.
I'll look into the tcp stream when I get some time.

**Comment by alexdalitz** [comment]
Awesome - thanks loads for your help!

My suspicion is that the TCP handler is not correctly joining multiple DNS packet fragments, but I have no direct proof, nor idea what may be causing this problem.

Thanks!


Alex.

**Comment by nwitkowski** [comment]
Chances are you are right. I was glad to see the decoder working with such a large message (30475 bytes). I'll probably end up printing the TCP packet size in the log file to see what's going on.

**Comment by nwitkowski** [comment]
So I found what the problem is. CacheData does a deep clone of a message with the following:
```Ruby
       def message=(m)
         @expiration = get_expiration(m)
         @message = Message.decode(m.encode)
         @message.cached = true
       end
```
The encoding "corrupts" the message and then the "decoding" raises an exception.
I looked around in the source code and couldn't find a way to disable caching.
One way to solve the issue would be to fix the message encoding.
Another option is to use the original message buffer and decode it from there in CacheData itself.
Another way to solve the issue it to use canonical labels when doing a msg.put_rr in the encode method of Message. We could then have a canonical boolean parameter to the Message encode function.

**Comment by nwitkowski** [comment]
Not sure if this is the way you want to go but my test and current changes are in this pull request:
https://github.com/alexdalitz/dnsruby/pull/109

**Comment by alexdalitz** [comment]
Thanks loads for that!

@KINGSABRI : could you please test master to make sure it works for you? Once I get confirmation, then I will make a new release of dnruby - 1.60.0

Thanks everyone!

**Comment by alexdalitz** [comment]
@KINGSABRI  : have you had a chance to look at this, please? It would be great if you could please confirm that the issue is fixed before I make the new release...

**Comment by KINGSABRI** [comment]
Hi @alexdalitz,
Sorry for being away for a long time. I'll test it today

**Comment by KINGSABRI** [comment]
Confirmed, the issue has been fixed 

```
pry --simple-prompt
```

```ruby

>> Dir.chdir "dnsruby/lib"
>> $:.unshift Dir.pwd

>> require 'dnsruby'
>> Dnsruby::VERSION  #=> "1.59.3"
>> resolver = Dnsruby::Resolver.new
>> query    = resolver.query('207.46.197.32', 'PTR', 'IN')

#<Dnsruby::Message:0x00000003076220
 @additional=[#<#<Class:0x007ff5d009bbb8>:0x007ff5d009ba50 @klass=CLASS1500, @name=#<Dnsruby::Name: .>, @options=nil, @ttl=32768, @type=OPT>],
 @answer=
  [#<Dnsruby::RR::IN::PTR:0x0000000306bac8
    @domainname=#<Dnsruby::Name: windows2000.com.>,
    @klass=IN,
    @name=#<Dnsruby::Name: 32.197.46.207.in-addr.arpa.>,
    @rdata=#<Dnsruby::Name: windows2000.com.>,
    @ttl=3600,
    @type=PTR>,
   #<Dnsruby::RR::IN::PTR:0x00000003069fc0
    @domainname=#<Dnsruby::Name: windows2000.net.>,
    @klass=IN,
    @name=#<Dnsruby::Name: 32.197.46.207.in-addr.arpa.>,
    @rdata=#<Dnsruby::Name: windows2000.net.>,
    @ttl=3600,
    @type=PTR>,
..snippt...


query.answer.size #=> 1042

```

**Comment by alexdalitz** [comment]
Thanks!
