### ISSUE TITLE
Delete all NAPTR records for a name results in an exception

### ISSUE THREAD

**Issue by cdonadeo** [alexdalitz/dnsruby#131]
Take this example intended to delete all `NAPTR` records with name `somename.mysubdomain.example.net`:
```
resolver = Dnsruby::Resolver.new({nameserver: 'mymaster.example.net'})
update = Dnsruby::Update.new('mysubdomain.example.net')
update.delete('somename.mysubdomain.example.net', 'NAPTR')
response = resolver.send_message(update)
```
The above pattern is shown (but for `A` records instead of `NAPTR`) in the [comments for update.rb](https://github.com/alexdalitz/dnsruby/blob/master/lib/dnsruby/update.rb#L60).  This results in an exception:
```
TypeError: no implicit conversion of nil into Integer
	from /Users/chrisdonadeo/Repos/Dashboard/.gems/gems/dnsruby-1.60.1/lib/dnsruby/message/encoder.rb:19:in `pack'
	from /Users/chrisdonadeo/Repos/Dashboard/.gems/gems/dnsruby-1.60.1/lib/dnsruby/message/encoder.rb:19:in `put_pack'
	from /Users/chrisdonadeo/Repos/Dashboard/.gems/gems/dnsruby-1.60.1/lib/dnsruby/resource/NAPTR.rb:79:in `encode_rdata'
	from /Users/chrisdonadeo/Repos/Dashboard/.gems/gems/dnsruby-1.60.1/lib/dnsruby/message/encoder.rb:51:in `block in put_rr'
	from /Users/chrisdonadeo/Repos/Dashboard/.gems/gems/dnsruby-1.60.1/lib/dnsruby/message/encoder.rb:29:in `put_length16'
	from /Users/chrisdonadeo/Repos/Dashboard/.gems/gems/dnsruby-1.60.1/lib/dnsruby/message/encoder.rb:51:in `put_rr'
	from /Users/chrisdonadeo/Repos/Dashboard/.gems/gems/dnsruby-1.60.1/lib/dnsruby/message/message.rb:557:in `block (3 levels) in encode'
	from /Users/chrisdonadeo/Repos/Dashboard/.gems/gems/dnsruby-1.60.1/lib/dnsruby/message/message.rb:556:in `each'
	from /Users/chrisdonadeo/Repos/Dashboard/.gems/gems/dnsruby-1.60.1/lib/dnsruby/message/message.rb:556:in `block (2 levels) in encode'
	from /Users/chrisdonadeo/Repos/Dashboard/.gems/gems/dnsruby-1.60.1/lib/dnsruby/message/message.rb:555:in `each'
	from /Users/chrisdonadeo/Repos/Dashboard/.gems/gems/dnsruby-1.60.1/lib/dnsruby/message/message.rb:555:in `block in encode'
	from /Users/chrisdonadeo/Repos/Dashboard/.gems/gems/dnsruby-1.60.1/lib/dnsruby/message/encoder.rb:6:in `initialize'
	from /Users/chrisdonadeo/Repos/Dashboard/.gems/gems/dnsruby-1.60.1/lib/dnsruby/message/message.rb:548:in `new'
	from /Users/chrisdonadeo/Repos/Dashboard/.gems/gems/dnsruby-1.60.1/lib/dnsruby/message/message.rb:548:in `encode'
	from /Users/chrisdonadeo/Repos/Dashboard/.gems/gems/dnsruby-1.60.1/lib/dnsruby/packet_sender.rb:720:in `make_query_packet'
	from /Users/chrisdonadeo/Repos/Dashboard/.gems/gems/dnsruby-1.60.1/lib/dnsruby/packet_sender.rb:334:in `send_async'
	from /Users/chrisdonadeo/Repos/Dashboard/.gems/gems/dnsruby-1.60.1/lib/dnsruby/resolver.rb:1009:in `block (3 levels) in tick'
	from /Users/chrisdonadeo/Repos/Dashboard/.gems/gems/dnsruby-1.60.1/lib/dnsruby/resolver.rb:995:in `each'
	from /Users/chrisdonadeo/Repos/Dashboard/.gems/gems/dnsruby-1.60.1/lib/dnsruby/resolver.rb:995:in `block (2 levels) in tick'
	from /Users/chrisdonadeo/Repos/Dashboard/.gems/gems/dnsruby-1.60.1/lib/dnsruby/resolver.rb:985:in `each'
	from /Users/chrisdonadeo/Repos/Dashboard/.gems/gems/dnsruby-1.60.1/lib/dnsruby/resolver.rb:985:in `block in tick'
	from /Users/chrisdonadeo/Repos/Dashboard/.gems/gems/dnsruby-1.60.1/lib/dnsruby/resolver.rb:983:in `synchronize'
	from /Users/chrisdonadeo/Repos/Dashboard/.gems/gems/dnsruby-1.60.1/lib/dnsruby/resolver.rb:983:in `tick'
	from /Users/chrisdonadeo/Repos/Dashboard/.gems/gems/dnsruby-1.60.1/lib/dnsruby/select_thread.rb:807:in `block in send_tick_to_observers'
	from /Users/chrisdonadeo/Repos/Dashboard/.gems/gems/dnsruby-1.60.1/lib/dnsruby/select_thread.rb:806:in `each'
	from /Users/chrisdonadeo/Repos/Dashboard/.gems/gems/dnsruby-1.60.1/lib/dnsruby/select_thread.rb:806:in `send_tick_to_observers'
	from /Users/chrisdonadeo/Repos/Dashboard/.gems/gems/dnsruby-1.60.1/lib/dnsruby/select_thread.rb:171:in `do_select'
	from /Users/chrisdonadeo/Repos/Dashboard/.gems/gems/dnsruby-1.60.1/lib/dnsruby/select_thread.rb:153:in `block in check_select_thread_synchronized'
```

**Comment by alexdalitz** [comment]
Have you tried the latest master? There was a patch sent in for this very recently...

**Comment by cdonadeo** [comment]
Hey Alex,

I just tried the same thing against `master@29eaeb5` and this does still seem to happen.

**Comment by alexdalitz** [comment]
OK, thanks for that. I'll try my best to look at this soon (including implementing a proper test case). However, I'm afraid I'm ludicrously busy at the moment, so can't promise to fix this immediately.

**Comment by alexdalitz** [comment]
Sorry about the delay. However, I've now discovered a bug in the NAPTR record encoding which did not correctly handle the null rdata strings required by update packets. I've pushed a fix for this to master.
Could you please give it a shot and let me know if you still have issues?
Thanks!

Alex.

**Comment by cdonadeo** [comment]
Testing against `master@57648af`, I am no longer able to reproduce the issue.  Thanks a lot!
