### ISSUE TITLE
fatal: No live threads left: Deadlock? when "IDN support" exception is raised

### ISSUE THREAD

**Issue by fschwahn** [alexdalitz/dnsruby#146]
I have had problems with dnsruby "crashing" when it encounters a string which should have been punycoded. See the following example session:

```
irb(main):002:0> require "dnsruby"
=> true
irb(main):003:0> resolver = Dnsruby::Resolver.new(nameserver: ["8.8.8.8", "8.8.4.4"])
=> #<Dnsruby::Resolver:0x00007fa4c5b89cc0 @resolver_ruby=nil, @src_address=nil, @src_address6=nil, @single_res_mutex=#<Thread::Mutex:0x00007fa4c5b89c48>, @configured=true, @do_caching=true, @config=Config - nameservers : 8.8.8.8, 8.8.4.4,  domain : [#<Dnsruby::Name::Label unix>, #<Dnsruby::Name::Label net>], search : local,  ndots : 1, @do_validation=false, @query_timeout=0, @retry_delay=5, @retry_times=1, @packet_timeout=5, @port=53, @udp_size=4096, @dnssec=false, @use_tcp=false, @no_tcp=false, @tcp_pipelining=false, @tcp_pipelining_max_queries=5, @tsig=nil, @ignore_truncation=false, @src_port=[0], @recurse=true, @single_resolvers=[#<Dnsruby::PacketSender:0x00007fa4c5b80ff8 @ipv6=false, @packet_timeout=5, @port=53, @udp_size=4096, @dnssec=false, @use_tcp=false, @no_tcp=false, @tsig=nil, @ignore_truncation=false, @src_address="0.0.0.0", @src_address6="::", @src_port=[0], @recurse=true, @tcp_pipelining=false, @tcp_pipelining_max_queries=5, @use_counts={}, @server="8.8.8.8">, #<Dnsruby::PacketSender:0x00007fa4c5b7b288 @ipv6=false, @packet_timeout=5, @port=53, @udp_size=4096, @dnssec=false, @use_tcp=false, @no_tcp=false, @tsig=nil, @ignore_truncation=false, @src_address="0.0.0.0", @src_address6="::", @src_port=[0], @recurse=true, @tcp_pipelining=false, @tcp_pipelining_max_queries=5, @use_counts={}, @server="8.8.4.4">]>
irb(main):004:0> resolver.query("google.com", "MX")
=> #<Dnsruby::Message:0x00007fa4c5068f80 @header=#<Dnsruby::Header:0x00007fa4c5b73c68 @id=75, @qr=true, @opcode=Query, @aa=false, @ad=false, @tc=false, @rd=true, @ra=true, @cd=false, @rcode=NOERROR, @qdcount=1, @nscount=0, @ancount=5, @arcount=0>, @question=[#<Dnsruby::Question:0x00007fa4c5b73380 @qtype=MX, @qclass=IN, @qname=#<Dnsruby::Name: google.com.>>], @answer=[#<Dnsruby::RR::IN::MX:0x00007fa4c5b71c10 @rdata=[40, #<Dnsruby::Name: alt3.aspmx.l.google.com.>], @preference=40, @exchange=#<Dnsruby::Name: alt3.aspmx.l.google.com.>, @name=#<Dnsruby::Name: google.com.>, @ttl=599, @type=MX, @klass=IN>, #<Dnsruby::RR::IN::MX:0x00007fa4c5b703d8 @rdata=[30, #<Dnsruby::Name: alt2.aspmx.l.google.com.>], @preference=30, @exchange=#<Dnsruby::Name: alt2.aspmx.l.google.com.>, @name=#<Dnsruby::Name: google.com.>, @ttl=599, @type=MX, @klass=IN>, #<Dnsruby::RR::IN::MX:0x00007fa4c5b69858 @rdata=[50, #<Dnsruby::Name: alt4.aspmx.l.google.com.>], @preference=50, @exchange=#<Dnsruby::Name: alt4.aspmx.l.google.com.>, @name=#<Dnsruby::Name: google.com.>, @ttl=599, @type=MX, @klass=IN>, #<Dnsruby::RR::IN::MX:0x00007fa4c5b631b0 @rdata=[10, #<Dnsruby::Name: aspmx.l.google.com.>], @preference=10, @exchange=#<Dnsruby::Name: aspmx.l.google.com.>, @name=#<Dnsruby::Name: google.com.>, @ttl=599, @type=MX, @klass=IN>, #<Dnsruby::RR::IN::MX:0x00007fa4c5b60c80 @rdata=[20, #<Dnsruby::Name: alt1.aspmx.l.google.com.>], @preference=20, @exchange=#<Dnsruby::Name: alt1.aspmx.l.google.com.>, @name=#<Dnsruby::Name: google.com.>, @ttl=599, @type=MX, @klass=IN>], @authority=[], @additional=[], @tsigstate=:Unsigned, @signing=false, @tsigkey=nil, @answerfrom="8.8.8.8", @answerip="8.8.8.8", @send_raw=false, @do_validation=true, @do_caching=true, @security_level=UNCHECKED, @security_error=nil, @cached=false, @answersize=136>
irb(main):005:0> resolver.query("google.com", "MX")
=> #<Dnsruby::Message:0x00007fa4c4b04a80 @header=#<Dnsruby::Header:0x00007fa4c4b045a8 @id=46884, @qr=true, @opcode=Query, @aa=false, @ad=false, @tc=false, @rd=true, @ra=true, @cd=false, @rcode=NOERROR, @qdcount=1, @nscount=0, @ancount=5, @arcount=0>, @question=[#<Dnsruby::Question:0x00007fa4c4affd28 @qtype=MX, @qclass=IN, @qname=#<Dnsruby::Name: google.com.>>], @answer=[#<Dnsruby::RR::IN::MX:0x00007fa4c4afe388 @rdata=[40, #<Dnsruby::Name: alt3.aspmx.l.google.com.>], @preference=40, @exchange=#<Dnsruby::Name: alt3.aspmx.l.google.com.>, @name=#<Dnsruby::Name: google.com.>, @ttl=597, @type=MX, @klass=IN>, #<Dnsruby::RR::IN::MX:0x00007fa4c5b03f08 @rdata=[30, #<Dnsruby::Name: alt2.aspmx.l.google.com.>], @preference=30, @exchange=#<Dnsruby::Name: alt2.aspmx.l.google.com.>, @name=#<Dnsruby::Name: google.com.>, @ttl=597, @type=MX, @klass=IN>, #<Dnsruby::RR::IN::MX:0x00007fa4c5b02608 @rdata=[50, #<Dnsruby::Name: alt4.aspmx.l.google.com.>], @preference=50, @exchange=#<Dnsruby::Name: alt4.aspmx.l.google.com.>, @name=#<Dnsruby::Name: google.com.>, @ttl=597, @type=MX, @klass=IN>, #<Dnsruby::RR::IN::MX:0x00007fa4c5b00f38 @rdata=[10, #<Dnsruby::Name: aspmx.l.google.com.>], @preference=10, @exchange=#<Dnsruby::Name: aspmx.l.google.com.>, @name=#<Dnsruby::Name: google.com.>, @ttl=597, @type=MX, @klass=IN>, #<Dnsruby::RR::IN::MX:0x00007fa4c5afb858 @rdata=[20, #<Dnsruby::Name: alt1.aspmx.l.google.com.>], @preference=20, @exchange=#<Dnsruby::Name: alt1.aspmx.l.google.com.>, @name=#<Dnsruby::Name: google.com.>, @ttl=597, @type=MX, @klass=IN>], @authority=[], @additional=[], @tsigstate=:Unsigned, @signing=false, @tsigkey=nil, @answerfrom=nil, @answerip=nil, @send_raw=false, @do_validation=true, @do_caching=true, @security_level=UNCHECKED, @security_error=nil, @cached=true>
irb(main):006:0> resolver.query("googlöe.com", "MX")
Dnsruby::OtherResolvError: IDN support currently requires punycode string
	from /Users/fabian/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.2/lib/dnsruby/message/encoder.rb:39:in `rescue in put_string'
	from /Users/fabian/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.2/lib/dnsruby/message/encoder.rb:34:in `put_string'
	from /Users/fabian/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.2/lib/dnsruby/message/encoder.rb:80:in `put_label'
	from /Users/fabian/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.2/lib/dnsruby/message/encoder.rb:69:in `block in put_labels'
	from /Users/fabian/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.2/lib/dnsruby/message/encoder.rb:62:in `each_index'
	from /Users/fabian/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.2/lib/dnsruby/message/encoder.rb:62:in `put_labels'
	from /Users/fabian/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.2/lib/dnsruby/message/encoder.rb:58:in `put_name'
	from /Users/fabian/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.2/lib/dnsruby/message/message.rb:552:in `block (2 levels) in encode'
	from /Users/fabian/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.2/lib/dnsruby/message/message.rb:551:in `each'
	from /Users/fabian/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.2/lib/dnsruby/message/message.rb:551:in `block in encode'
	from /Users/fabian/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.2/lib/dnsruby/message/encoder.rb:6:in `initialize'
	from /Users/fabian/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.2/lib/dnsruby/message/message.rb:548:in `new'
	from /Users/fabian/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.2/lib/dnsruby/message/message.rb:548:in `encode'
	from /Users/fabian/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.2/lib/dnsruby/packet_sender.rb:720:in `make_query_packet'
	from /Users/fabian/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.2/lib/dnsruby/packet_sender.rb:334:in `send_async'
	from /Users/fabian/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.2/lib/dnsruby/resolver.rb:1010:in `block (3 levels) in tick'
	from /Users/fabian/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.2/lib/dnsruby/resolver.rb:996:in `each'
	from /Users/fabian/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.2/lib/dnsruby/resolver.rb:996:in `block (2 levels) in tick'
	from /Users/fabian/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.2/lib/dnsruby/resolver.rb:986:in `each'
	from /Users/fabian/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.2/lib/dnsruby/resolver.rb:986:in `block in tick'
	from /Users/fabian/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.2/lib/dnsruby/resolver.rb:984:in `synchronize'
	from /Users/fabian/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.2/lib/dnsruby/resolver.rb:984:in `tick'
	from /Users/fabian/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.2/lib/dnsruby/resolver.rb:919:in `send_async'
	from /Users/fabian/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.2/lib/dnsruby/resolver.rb:401:in `send_async'
	from /Users/fabian/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.2/lib/dnsruby/resolver.rb:251:in `send_message'
	from /Users/fabian/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.2/lib/dnsruby/resolver.rb:203:in `query'
	from (irb):6
	from /Users/fabian/.rbenv/versions/2.3.7/bin/irb:11:in `<main>'
irb(main):007:0> resolver.query("google.com", "MX")
=> #<Dnsruby::Message:0x00007fa4c5ac9808 @header=#<Dnsruby::Header:0x00007fa4c5ac9060 @id=3876, @qr=true, @opcode=Query, @aa=false, @ad=false, @tc=false, @rd=true, @ra=true, @cd=false, @rcode=NOERROR, @qdcount=1, @nscount=0, @ancount=5, @arcount=0>, @question=[#<Dnsruby::Question:0x00007fa4c5ac84f8 @qtype=MX, @qclass=IN, @qname=#<Dnsruby::Name: google.com.>>], @answer=[#<Dnsruby::RR::IN::MX:0x00007fa4c5ac2c60 @rdata=[40, #<Dnsruby::Name: alt3.aspmx.l.google.com.>], @preference=40, @exchange=#<Dnsruby::Name: alt3.aspmx.l.google.com.>, @name=#<Dnsruby::Name: google.com.>, @ttl=592, @type=MX, @klass=IN>, #<Dnsruby::RR::IN::MX:0x00007fa4c5ac1450 @rdata=[30, #<Dnsruby::Name: alt2.aspmx.l.google.com.>], @preference=30, @exchange=#<Dnsruby::Name: alt2.aspmx.l.google.com.>, @name=#<Dnsruby::Name: google.com.>, @ttl=592, @type=MX, @klass=IN>, #<Dnsruby::RR::IN::MX:0x00007fa4c4a8fd48 @rdata=[50, #<Dnsruby::Name: alt4.aspmx.l.google.com.>], @preference=50, @exchange=#<Dnsruby::Name: alt4.aspmx.l.google.com.>, @name=#<Dnsruby::Name: google.com.>, @ttl=592, @type=MX, @klass=IN>, #<Dnsruby::RR::IN::MX:0x00007fa4c4a8e678 @rdata=[10, #<Dnsruby::Name: aspmx.l.google.com.>], @preference=10, @exchange=#<Dnsruby::Name: aspmx.l.google.com.>, @name=#<Dnsruby::Name: google.com.>, @ttl=592, @type=MX, @klass=IN>, #<Dnsruby::RR::IN::MX:0x00007fa4c4a8ce68 @rdata=[20, #<Dnsruby::Name: alt1.aspmx.l.google.com.>], @preference=20, @exchange=#<Dnsruby::Name: alt1.aspmx.l.google.com.>, @name=#<Dnsruby::Name: google.com.>, @ttl=592, @type=MX, @klass=IN>], @authority=[], @additional=[], @tsigstate=:Unsigned, @signing=false, @tsigkey=nil, @answerfrom=nil, @answerip=nil, @send_raw=false, @do_validation=true, @do_caching=true, @security_level=UNCHECKED, @security_error=nil, @cached=true>
irb(main):008:0> resolver.query("google.com", "MX")
=> #<Dnsruby::Message:0x00007fa4c5a70cd0 @header=#<Dnsruby::Header:0x00007fa4c5a707f8 @id=53363, @qr=true, @opcode=Query, @aa=false, @ad=false, @tc=false, @rd=true, @ra=true, @cd=false, @rcode=NOERROR, @qdcount=1, @nscount=0, @ancount=5, @arcount=0>, @question=[#<Dnsruby::Question:0x00007fa4c5a71040 @qtype=MX, @qclass=IN, @qname=#<Dnsruby::Name: google.com.>>], @answer=[#<Dnsruby::RR::IN::MX:0x00007fa4c5a6aab0 @rdata=[40, #<Dnsruby::Name: alt3.aspmx.l.google.com.>], @preference=40, @exchange=#<Dnsruby::Name: alt3.aspmx.l.google.com.>, @name=#<Dnsruby::Name: google.com.>, @ttl=591, @type=MX, @klass=IN>, #<Dnsruby::RR::IN::MX:0x00007fa4c5a69228 @rdata=[30, #<Dnsruby::Name: alt2.aspmx.l.google.com.>], @preference=30, @exchange=#<Dnsruby::Name: alt2.aspmx.l.google.com.>, @name=#<Dnsruby::Name: google.com.>, @ttl=591, @type=MX, @klass=IN>, #<Dnsruby::RR::IN::MX:0x00007fa4c5a63ad0 @rdata=[50, #<Dnsruby::Name: alt4.aspmx.l.google.com.>], @preference=50, @exchange=#<Dnsruby::Name: alt4.aspmx.l.google.com.>, @name=#<Dnsruby::Name: google.com.>, @ttl=591, @type=MX, @klass=IN>, #<Dnsruby::RR::IN::MX:0x00007fa4c5a624a0 @rdata=[10, #<Dnsruby::Name: aspmx.l.google.com.>], @preference=10, @exchange=#<Dnsruby::Name: aspmx.l.google.com.>, @name=#<Dnsruby::Name: google.com.>, @ttl=591, @type=MX, @klass=IN>, #<Dnsruby::RR::IN::MX:0x00007fa4c5a60bc8 @rdata=[20, #<Dnsruby::Name: alt1.aspmx.l.google.com.>], @preference=20, @exchange=#<Dnsruby::Name: alt1.aspmx.l.google.com.>, @name=#<Dnsruby::Name: google.com.>, @ttl=591, @type=MX, @klass=IN>], @authority=[], @additional=[], @tsigstate=:Unsigned, @signing=false, @tsigkey=nil, @answerfrom=nil, @answerip=nil, @send_raw=false, @do_validation=true, @do_caching=true, @security_level=UNCHECKED, @security_error=nil, @cached=true>
irb(main):009:0> resolver.query("googlöe.com", "MX")
Dnsruby::ResolvTimeout: Query timed out
	from /Users/fabian/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.2/lib/dnsruby/resolver.rb:257:in `send_message'
	from /Users/fabian/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.2/lib/dnsruby/resolver.rb:203:in `query'
	from (irb):9
	from /Users/fabian/.rbenv/versions/2.3.7/bin/irb:11:in `<main>'
irb(main):010:0> resolver.query("googlöe.com", "MX")
fatal: No live threads left. Deadlock?
	from /Users/fabian/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.2/lib/dnsruby/resolver.rb:253:in `pop'
	from /Users/fabian/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.2/lib/dnsruby/resolver.rb:253:in `send_message'
	from /Users/fabian/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/dnsruby-1.60.2/lib/dnsruby/resolver.rb:203:in `query'
	from (irb):10
	from /Users/fabian/.rbenv/versions/2.3.7/bin/irb:11:in `<main>'
```

I have a suspicion that this happens because the error is just raised inside the thread, while other exception are gracefully pushed to the queue. This is just hunch however, I've only read the code very superficially.

**Comment by fschwahn** [comment]
No apologies necessary, thanks for the amazing gem ☺️

**Comment by alexdalitz** [comment]
Thanks for bearing with me.

As promised, this issue is now fixed.

Could you please confirm?

Thanks!

**Comment by alexdalitz** [comment]
(on master, that is)

**Comment by fschwahn** [comment]
I just tested it (with the same steps as above), and there are no more Deadlocks. 

Just one thing which seems weird: When I pass in the non-punycoded domain the second time (were the deadlock happened before), I get a `Dnsruby::ResolvTimeout: Query timed out`, instead of `IDN support currently requires punycode string`. Not sure if this is a problem at all, just something I noticed.

**Comment by alexdalitz** [comment]
Yeah - good point - thanks - I'll fix that now

**Comment by alexdalitz** [comment]
OK - this should be fixed now - if you get the chance, could you please confirm so I can close the isse? Thanks!

**Comment by fschwahn** [comment]
Seems to work now 👍
